jms_serializer:
    handlers:
        datetime:
            default_format: "d/m/Y"
            default_timezone: "Europe/Madrid"
    default_context:
        serialization:
            enable_max_depth_checks: true
        deserialization:
            enable_max_depth_checks: true
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'

when@prod:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION

when@dev:
    jms_serializer:
        visitors:
            json_serialization:
                options:
                    - JSON_PRETTY_PRINT
                    - JSON_UNESCAPED_SLASHES
                    - JSON_PRESERVE_ZERO_FRACTION
