twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    globals:
        twitter_url: '%twitter_url%'
        facebook_url: '%facebook_url%'
        youtube_url: '%youtube_url%'
        google_plus_url: '%google_plus_url%'
        urlLogos: '%urlLogos%'

when@test:
    twig:
        strict_variables: true
